version: "3"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "bankapp"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql

  api:
    build: ./api/java
    restart: always
    expose:
      - 8080
    depends_on:
      - db

  frontend:
    build: ./frontend
    restart: always
    expose:
      - 3000
    depends_on:
      - api

volumes:
  my-db:
