# Generated by Django 4.0.1 on 2022-01-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(max_length=20)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('iban', models.CharField(max_length=20)),
                ('bic', models.CharField(max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(max_length=3)),
            ],
        ),
    ]
