# Generated by Django 4.0.1 on 2022-01-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=6)),
                ('svnr', models.IntegerField()),
                ('date_of_birth', models.DateTimeField()),
                ('street_with_no', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sender_account', models.IntegerField()),
                ('receiver_account', models.IntegerField()),
                ('transaction_type', models.CharField(max_length=20)),
                ('date_of_occurrence', models.DateTimeField(auto_now_add=True)),
                ('payment_reference', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transaction_limit', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='iban',
            field=models.CharField(max_length=27),
        ),
    ]
