# Generated by Django 4.0.1 on 2022-01-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0004_transactiontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetype',
            name='description',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='description',
            field=models.CharField(max_length=30),
        ),
    ]
