# Generated by Django 4.0.1 on 2022-01-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0005_alter_expensetype_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='expense_type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
